In [1]:
import pandas as pd, matplotlib.pyplot as plt
from datasets import load_dataset, Dataset

# Loading data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()  # Changed: 'to pandas' to 'to_pandas()'

# Data cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

c:\Users\Greg\anaconda3\envs\Python_Data_Project_1_env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df.index.name = 'job_index'
df.index.name

'job_index'

In [5]:
df.sample(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
45891,Senior Data Analyst,Senior Data Analyst,"Norcross, GA",via BeBee,Full-time,False,Georgia,2023-07-27 06:55:29,True,False,United States,NaN,NaN,NaN,firstPRO 360,"['excel', 'powerpoint']","{'analyst_tools': ['excel', 'powerpoint']}"
118840,Data Scientist,Data инженер,"Moscow, Russia",via hh.ru,Full-time,False,Russia,2023-06-20 08:30:41,True,False,Russia,NaN,NaN,NaN,Центральный банк Российской Федерации,"['sql', 'python', 'hadoop', 'spark', 'airflow'...","{'analyst_tools': ['qlik', 'power bi', 'tablea..."
526426,Software Engineer,Platform engineer API Platforms,"Stockholm, Sweden",via Trabajo.org,Full-time,False,Sweden,2023-07-27 11:48:03,True,False,Sweden,NaN,NaN,NaN,H&M Group,"['powershell', 'c#', 'typescript', 'azure', 'g...","{'cloud': ['azure', 'gcp'], 'other': ['github'..."

In [10]:
median_pivot = df.pivot_table(
    values='salary_year_avg',  
    index='job_title_short',
    aggfunc=['median','mean','max']
)
median_pivot

                                   median            mean             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  85000.0    91082.612833        387460.0
Cloud Engineer                    90000.0   111268.453846        280000.0
Data Analyst                      90000.0    93841.907854        650000.0
Data Engineer                    125000.0   130125.604250        525000.0
Data Scientist                   127500.0   135988.837171        960000.0
Machine Learning Engineer        106415.0   126774.315972        325000.0
Senior Data Analyst              111175.0   113911.363665        425000.0
Senior Data Engineer             147500.0   145840.611624        425000.0
Senior Data Scientist            155500.0   154206.292996        890000.0
Software Engineer                 99150.0   113393.760054        375000.0

In [17]:
median_pivot.sort_values(by=('median', 'salary_year_avg'), ascending=False) #provide the column as a tuple
median_pivot

                                   median            mean             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  85000.0    91082.612833        387460.0
Cloud Engineer                    90000.0   111268.453846        280000.0
Data Analyst                      90000.0    93841.907854        650000.0
Data Engineer                    125000.0   130125.604250        525000.0
Data Scientist                   127500.0   135988.837171        960000.0
Machine Learning Engineer        106415.0   126774.315972        325000.0
Senior Data Analyst              111175.0   113911.363665        425000.0
Senior Data Engineer             147500.0   145840.611624        425000.0
Senior Data Scientist            155500.0   154206.292996        890000.0
Software Engineer                 99150.0   113393.760054        375000.0

In [19]:
median_pivot.sort_index()
median_pivot

                                   median            mean             max
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  85000.0    91082.612833        387460.0
Cloud Engineer                    90000.0   111268.453846        280000.0
Data Analyst                      90000.0    93841.907854        650000.0
Data Engineer                    125000.0   130125.604250        525000.0
Data Scientist                   127500.0   135988.837171        960000.0
Machine Learning Engineer        106415.0   126774.315972        325000.0
Senior Data Analyst              111175.0   113911.363665        425000.0
Senior Data Engineer             147500.0   145840.611624        425000.0
Senior Data Scientist            155500.0   154206.292996        890000.0
Software Engineer                 99150.0   113393.760054        375000.0